# fly.toml app configuration file generated for remix-jokes-luismartinez on 2023-07-11T20:16:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-jokes-luismartinez"
primary_region = "mad"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
